/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmitseprocesstools.view;

import javax.swing.JOptionPane;
import rmitseprocesstools.controller.AuthController;

/**
 *
 * @author billy
 */
public class BusinessRegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form BusinessRegistrationView
     */
    public BusinessRegistrationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBusinessName = new javax.swing.JLabel();
        txtBusinessPhone = new javax.swing.JTextField();
        jpfBusinessPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        cmbBusinessQuestion = new javax.swing.JComboBox<>();
        lblBusinessPassword = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        lblBusinessAddress = new javax.swing.JLabel();
        lblBusinessUsername = new javax.swing.JLabel();
        jpfConfirmBusinessPassword = new javax.swing.JPasswordField();
        txtBusinessAddress = new javax.swing.JTextField();
        txtBusinessUserName = new javax.swing.JTextField();
        lblConfirmBusinessPassword = new javax.swing.JLabel();
        txtBusinessStartTime = new javax.swing.JTextField();
        txtBusinessStartTime1 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtBusinessAnswer = new javax.swing.JTextField();
        lblBusinessEndTime = new javax.swing.JLabel();
        lblBusinessStartTime = new javax.swing.JLabel();
        txtBusinessName = new javax.swing.JTextField();
        lblBusinessHours = new javax.swing.JLabel();
        lblBusinessAnswer = new javax.swing.JLabel();
        lblBusinessContactNumber = new javax.swing.JLabel();
        lblBusinessQuestion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBusinessName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessName.setText("Business Name");

        txtBusinessPhone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jpfBusinessPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        cmbBusinessQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbBusinessQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mother's Maiden Name?", "Your First Pets Name?", "Your Favourite Book?", "Your First School Teacher?" }));

        lblBusinessPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessPassword.setText("Business Password");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblBusinessAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessAddress.setText("Business Address");

        lblBusinessUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessUsername.setText("Business Username (Email)");

        jpfConfirmBusinessPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtBusinessAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBusinessAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessAddressActionPerformed(evt);
            }
        });

        txtBusinessUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblConfirmBusinessPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblConfirmBusinessPassword.setText("Confirm Password");

        txtBusinessStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessStartTimeActionPerformed(evt);
            }
        });

        txtBusinessStartTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessStartTime1ActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Business Registration Form");

        txtBusinessAnswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblBusinessEndTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessEndTime.setText("End Time");

        lblBusinessStartTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessStartTime.setText("Start Time");

        txtBusinessName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBusinessName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusinessNameActionPerformed(evt);
            }
        });

        lblBusinessHours.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessHours.setText("Business Hours");

        lblBusinessAnswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessAnswer.setText("Business Answer");

        lblBusinessContactNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessContactNumber.setText("Business Contact Number");

        lblBusinessQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBusinessQuestion.setText("Business Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBusinessPassword)
                            .addComponent(lblBusinessUsername))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpfBusinessPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusinessUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBusinessName)
                                    .addComponent(lblConfirmBusinessPassword))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpfConfirmBusinessPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBusinessQuestion)
                                    .addComponent(lblBusinessAnswer)
                                    .addComponent(lblBusinessContactNumber)
                                    .addComponent(lblBusinessAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBusinessHours))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBusinessStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBusinessStartTime))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBusinessEndTime)
                                            .addComponent(txtBusinessStartTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtBusinessPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBusinessAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBusinessQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBusinessAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfBusinessPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessPassword))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfConfirmBusinessPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmBusinessPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusinessName)
                    .addComponent(txtBusinessName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusinessAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusinessAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessContactNumber))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusinessQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessQuestion))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessAnswer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusinessHours)
                    .addComponent(lblBusinessEndTime)
                    .addComponent(lblBusinessStartTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusinessStartTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if( jpfBusinessPassword.getText().equals(jpfConfirmBusinessPassword.getText())){

            AuthController authctrl = new AuthController();
            
            if(authctrl.registerBusiness(txtBusinessUserName.getText(), jpfBusinessPassword.getText(), txtBusinessName.getText(), "", txtBusinessAddress.getText(), txtBusinessPhone.getText(), cmbBusinessQuestion.getSelectedItem().toString(), txtBusinessAnswer.getText(), txtBusinessStartTime.getText(), txtBusinessStartTime1.getText())){
                JOptionPane.showMessageDialog(null,
                "Business Registration successfull.",
                "",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                BussinessOwnerOperationsView view = new BussinessOwnerOperationsView();
                view.updateBusinessData();
                view.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null,
                "Password confirmation is invalid. Please try again",
                "",JOptionPane.ERROR_MESSAGE);
            jpfBusinessPassword.setText("");
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
            LoginView view = new LoginView();
            view.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtBusinessAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusinessAddressActionPerformed

    private void txtBusinessStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusinessStartTimeActionPerformed

    private void txtBusinessStartTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessStartTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusinessStartTime1ActionPerformed

    private void txtBusinessNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusinessNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusinessNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusinessRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusinessRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusinessRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusinessRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusinessRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbBusinessQuestion;
    private javax.swing.JPasswordField jpfBusinessPassword;
    private javax.swing.JPasswordField jpfConfirmBusinessPassword;
    private javax.swing.JLabel lblBusinessAddress;
    private javax.swing.JLabel lblBusinessAnswer;
    private javax.swing.JLabel lblBusinessContactNumber;
    private javax.swing.JLabel lblBusinessEndTime;
    private javax.swing.JLabel lblBusinessHours;
    private javax.swing.JLabel lblBusinessName;
    private javax.swing.JLabel lblBusinessPassword;
    private javax.swing.JLabel lblBusinessQuestion;
    private javax.swing.JLabel lblBusinessStartTime;
    private javax.swing.JLabel lblBusinessUsername;
    private javax.swing.JLabel lblConfirmBusinessPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBusinessAddress;
    private javax.swing.JTextField txtBusinessAnswer;
    private javax.swing.JTextField txtBusinessName;
    private javax.swing.JTextField txtBusinessPhone;
    private javax.swing.JTextField txtBusinessStartTime;
    private javax.swing.JTextField txtBusinessStartTime1;
    private javax.swing.JTextField txtBusinessUserName;
    // End of variables declaration//GEN-END:variables
}
